name: IG Publisher

on: push

jobs:
  build-sushi-ig:
    name: Run SUSHI, build IG, publish IG to GH Pages
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Install SUSHI
        run: npm install -g fsh-sushi
      - name: Run SUSHI
        run: sushi . -o build
      - name: Install Jekyll
        run: gem install bundler jekyll
      - name: Download and run publisher
        run: |
          cd build
          chmod 755 _updatePublisher.sh
          chmod 755 _genonce.sh
          ./_updatePublisher.sh -f
          ./_genonce.sh
      # ---------------------
      # Trying to move this portion out to master workflow
      # - name: Publish IG output to github pages
      #   uses: peaceiris/actions-gh-pages@v3.5.7
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: build/output
      #     publish_branch: gh-pages
      #     user_name: 'github-actions[bot]'
      #     user_email: 'github-actions[bot]@users.noreply.github.com'
      # -----------------------
      # Problem below: Won't push and will fail if not changes to that directory
      # - name: Publish IG output to folder on github pages
      #   env:
      #     branch: $GITHUB_REF##*/
      #   run: |
      #     git fetch origin gh-pages
      #     git checkout gh-pages
      #     mkdir -p ${GITHUB_REF##*/}
      #     cd ${GITHUB_REF##*/}
      #     cp -R ../build/input/profiles/* ./
      #     git add .
      #     git commit -m "Publish build for branch ${GITHUB_REF##*/}"
      #     git push origin gh-pages